import PageBanner from '@/components/PageBanner'
import CTABand from '@/components/CTABand'
export const metadata = { title: 'Our Team — Cleo Consulting' }
const members = [
  { i: 'JS', name: 'Jai Singh', img: '/images/jai.webp', li: 'https://www.linkedin.com/in/singhjai77', bio: "Jai strives to be a perfectionist but most of the times fails miserably\u2026 after all.. no one\u2019s perfect. He is a graduate in Economics and English Literature and a Post Grad in Marketing and Information Technology. He has a sharp eye to recognize talent and; therefore; manages the recruitment efforts of the company. When he\u2019s not working, he\u2019s either spending some time with sheltered animals, traveling or just catching up on a movie \u2013 after taking permission from his six rescued dogs." },
  { i: 'VJ', name: 'Vic (Vikas) Joshi', img: '/images/vikas.webp', li: 'https://www.linkedin.com/in/joshivikas/', bio: "Vic is the funny guy in the team\u2026 a sense of humor, some may call boisterous, but most call it awesome. He is a Mathematics graduate and a Post Grad in Marketing and Information Technology. He is a pure sales guy, has a knack for closing deals having successfully delved into ERP sales, CAD/CAM-related services sales and now Professional Staffing. When he is not working, one can find him bike riding, running, golfing or playing pickle ball. His next ambition is to do a half Ironman by summer of 2027." },
  { i: 'MS', name: 'Manjeet Singh', img: '/images/manjeet.webp', li: 'https://www.linkedin.com/in/manjeetsingh1978/', bio: "Manjeet has spent over 20 years helping organizations figure out their biggest people challenges \u2014 across industries as varied as IT, Automotive, Manufacturing, R&D, Building Materials, and F&B. At Cleo, he's focused on building out the India staffing business, growing client partnerships, and delivering talent solutions that actually move the needle. He's the kind of HR leader who can sit in a boardroom and think strategically, then roll up his sleeves and get into the details \u2014 often on the same day. When he's not working, he's in the gym, in the pool, out running, or traveling somewhere new with his family." },
  { i: 'JJ', name: 'John Jimomi', img: '/images/john.webp', li: 'https://www.linkedin.com/in/john-jimomi-b384a613/', bio: "John Jimomi is a Senior Recruitment Specialist with several years of experience in technology hiring and full-cycle recruitment. He is a very soft-spoken, sincere, and honest man. He is passionate about his work and loves what he does. Skilled in identifying, engaging, and securing top talent across technology and non-technical functions, with expertise in sourcing, screening, headhunting, and offer negotiations. He is a married man juggling work and being a full-time dad to his son. Outside of work, he enjoys playing cricket, fishing, and spending quality time with his family." },
  { i: 'VB', name: 'Vignesh Babu', img: '/images/vignesh.webp', li: 'https://www.linkedin.com/in/vignesh-babu-/', bio: "Vignesh is a sales guy who believes that doing one thing really well will always beat doing a thousand things halfway \u2014 a mindset he picked up on the soccer field, where he spent years playing right defender for his school and university teams. Discipline, showing up consistently, and never cutting corners\u2026 soccer taught him all of it, and he brought every bit of that into his sales career. Off the clock, he's somehow always the guy who ends up becoming one of the kids the moment children are around \u2014 calm and grounded one minute, fully in the chaos the next. Bruce Lee said it best, and Vignesh lives it: \"I'm not afraid of the man who knows 1,000 kicks; I'm afraid of the man who has practiced one kick 1,000 times.\" For him, practice makes perfect." },
  { i: 'MD', name: 'Mohan Dhamodaran', img: '/images/mohan.webp', li: 'https://www.linkedin.com/in/mohan-dhamodaran-8a45a930b/', bio: "Mohan is the kind of person who leads with relationships first and figures out the rest from there. As a Business Expansion Consultant at Cleo, he works with clients across both public and private sectors, helping them find the right talent through a tailored, trust-first approach. He's genuinely energized by building partnerships that create long-term value \u2014 not just filling roles, but solving real problems. When he steps away from work, you'll find him reading up on history or emerging technologies, exploring somewhere new, or staying active. His take on growth: trust, consistency, and never stop learning." },
  { i: 'RP', name: 'Rajesh Pitti', img: '/images/rajesh.webp', li: 'https://www.linkedin.com/in/raj1985/', bio: "With an MBA and over 12 years in talent acquisition and team management, Rajesh has built a career on one simple idea: put the right people in the right rooms. He's led recruiting teams, worked across IT, admin, and government sectors, and genuinely loves the moment a great candidate finds a role that fits. Outside of work, family comes first \u2014 always. One of his favourite things to do with his loved ones is travel to devotional destinations and temple cities across India, exploring the country's spiritual and cultural heritage \u2014 something he holds close and keeps coming back to. He's also a big cricket and hockey fan; if there's a match on, he's watching it, and if he can get out on the pitch himself, even better." },
  { i: 'PM', name: 'Prudence Maria', img: '/images/prudence.webp', li: 'https://www.linkedin.com/in/prudence-maria-7a6b6022b/', bio: "Prudence Maria is a Talent Acquisition Specialist with experience in technical recruitment, supporting clients across the Canadian market. She specializes in sourcing and screening candidates for IT roles, with a strong focus on aligning talent with client requirements through effective resume evaluation and market research. Prudence contributes to her team by consistently delivering quality candidates and maintaining a structured, detail-oriented approach to recruitment. She is passionate about learning and continuously improving her expertise in emerging technologies and hiring trends. Outside of work, Prudence enjoys playing badminton, spending time with her family, and exploring personal wellness routines that bring balance and energy to her life." },
  { i: 'AM', name: 'Anil Munde', img: '/images/anil.webp', li: 'https://www.linkedin.com/in/anil-munde-5a24a09/', bio: "Anil wears a few different hats \u2014 and genuinely enjoys every single one of them. By day, he heads up Bench Sales and US IT Recruitment, connecting talented professionals with the right opportunities. By night (and honestly, in between client calls), he's a new dad to an amazing little boy \u2014 which, he'll tell you, is easily the best role he's taken on yet. He's a chess enthusiast who loves thinking a few moves ahead, a stock market follower who's always watching the numbers, and someone who can happily lose hours in a good conversation. Between the recruitment calls, the chess boards, the market updates, and the diaper duty\u2026 there's genuinely never a dull moment." },
  { i: 'RK', name: 'Ramesh K', img: '/images/rameshK.webp', li: 'https://www.linkedin.com/in/ramesh-k-aab4a017', bio: "Ramesh is a graduate in Computer Science Engineering and leads the sales team for Cleo. He has a very good understanding of all the technologies he sources and has a great zeal to learn new ones. He loves spending time with his family, which consists of his wife and 2 sons, and traveling a lot when he is not at work. He always believes in \u2013 \"You only live once, but if you do it right, once is enough\"." },
  { i: 'SP', name: 'Smita Pandey', img: '/images/smita.webp', li: 'https://www.linkedin.com/in/smitha-p-16420b16b/', bio: "With over 7 years in US staffing and recruitment, Smita has done it all \u2014 sourcing, screening, interviews, client relationships, offer negotiations, you name it. She's worked across industries, placing talent in both technical and non-technical roles, and she brings the same level of care and attention to every search. She's genuinely passionate about connecting people with opportunities that actually fit \u2014 not just on paper, but in practice." },
  { i: 'AP', name: 'Amit Patil', img: '/images/amit.webp', li: 'https://www.linkedin.com/in/amit-49369b49/', bio: "Amit is a detail-oriented individual who is very energetic, creative, eager to learn and adapt to new challenges, has excellent communication skills and strong interpersonal skills, excellent work ethics, team oriented with strong analytical and leadership qualities. He has a very good understanding of all the technologies that help him excel in his job. He's a natural leader with a sense of ownership and focus on quality even under high-pressure situations. He loves to travel and spend time with his family and friends." },
  { i: 'AJ', name: 'Asa Jimomi', img: '/images/asa.webp', li: 'https://www.linkedin.com/in/asa-jimomi-575262250/', bio: "Asa is a Political Science graduate with many talents and passions. Besides his academic accomplishments, he is an avid artist who loves to sketch and paint. He is a huge fan of the Marvel Universe, especially Loki. He loves the character's complexity and mischievous nature and finds the stories and mythology behind the character fascinating. Asa is always excited to discuss the latest Marvel movie or TV shows. His friends and family describe him as a kind and caring person who is easy to talk to and always puts others first. This quality alone makes him very personable and, therefore, a successful technical recruiter." },
  { i: 'SG', name: 'Sonali Gupta', img: '/images/sonali.webp', li: 'https://www.linkedin.com/in/sonali-gupta-42499b1ab/', bio: "Sonali is the kind of team member who just makes things run better. She brings strong communication and organizational skills to the table, a natural ability to connect with people, and a positive attitude that doesn't waver even when things get complicated. She's always looking to learn something new and genuinely enjoys being part of a collaborative team. Outside of work, she's spending time with family and friends, or is settled in with a good movie." },
  { i: 'RK', name: 'Ram Kumar', img: '/images/ram.webp', li: 'https://www.linkedin.com/in/ram-kumar-5bb228145/', bio: "Ramkumar approaches recruiting the same way he approaches the gym \u2014 with focus, patience, and a lot of persistence. When he's not finding the right candidate for a role, he's passionate about powerlifting and calisthenics, cooking something new, or keeping a close eye on how hiring trends are shifting across North America. Challenges that require real effort are kind of his thing." },
  { i: 'AS', name: 'Abhishek Swami', img: '/images/abhishek.webp', li: 'https://www.linkedin.com/in/abhishek-s-532991163/', bio: "Abhishek has spent over 12 years in US and Canadian recruitment, building deep expertise in IT hiring across banking and government clients. He knows the space well and knows what good talent looks like. Outside of work, he's a reader, a traveler, and someone who genuinely loves a long drive with no particular destination in mind." },
  { i: 'DS', name: 'Dhruv Pratap Singh', img: '/images/dhruv.webp', li: 'https://www.linkedin.com/in/dhruv-p-52086424b/', bio: "Dhruv's role is making sure everything runs smoothly behind the scenes, so the rest of the team can do their best work without the headaches. He holds an MBA in IT and brings a lot of energy and fun to the team alongside the more serious operational work. When he's not fixing a messy process, you'll find him out on a trek, strumming his guitar, or deep into a video game \u2014 a man of many interests." },
  { i: 'SG', name: 'Sachin Gaikwad', img: '/images/sachin.webp', li: 'https://www.linkedin.com/in/sachincgaikwad/', bio: "Sachin has spent over 10 years in talent acquisition, and in that time, he's worked across some genuinely varied and demanding sectors \u2014 IT, healthcare, public health, and state government, to name a few. He's led recruiting teams, managed client accounts, and handled the full hiring lifecycle from first outreach to final offer. He knows his way around complex requirements and takes the time to actually understand what a client needs rather than just sending resumes and hoping for the best. Outside of work, you'll find him keeping up with the latest in tech, finding ways to sharpen his craft, or spending time with family and friends." },
  { i: 'MS', name: 'Maninder Singh', img: '/images/maninder.webp', li: 'https://www.linkedin.com/in/iammsingh/', bio: "Maninder has always been genuinely curious about people \u2014 their stories, their goals, where they're headed. It's what pulled him into recruiting, and it's what's kept him there for several years. He builds real relationships, not just pipelines, and believes every conversation has something worth learning in it. Outside of work, he travels, explores new cultures, keeps up with the latest in tech, and spends time with family and friends. He'll also be the first to admit that, whether he's helping someone land their next role or simply sharing career advice, with his positivity and honesty, he always brings a little humor along for the ride \u2014 because why not?" },
]
export default function Team() {
  return (
    <>
      <PageBanner eyebrow="About Us" title="OUR<br>TEAM" num="02" bgImage="/images/team-fistbump.webp" />
      <div className="pg-body">
        <div className="team-list">
          {/* Cleo - top of page as the inspiration */}
          <div className="tm">
            <div className="tm-photo" style={{ padding: 0, overflow: 'hidden' }}><img src="/images/cleo.webp" alt="Cleo" style={{ width: '100%', height: '100%', objectFit: 'cover' }} /></div>
            <div className="tm-info">
              <div className="tm-name">Cleo</div>
              <div style={{ fontSize: '0.7rem', letterSpacing: '0.15em', textTransform: 'uppercase', color: 'var(--gold)', marginBottom: '0.75rem' }}>The Inspiration</div>
              <p className="tm-bio">Cleo is the inspiration behind this company. She came into Jai&rsquo;s life in 2008 at a bakery where their eyes met. From then till today they are inseparable. Cleo has taught us how to be grateful, how to love, respect and accept. She is honest, loyal, expressive and genuine &mdash; and we, as a company, shall offer our services with the same principles to our clients.</p>
            </div>
          </div>
          {members.map((m, idx) => (
            <div className={`tm`} key={idx}>
              <div className="tm-photo" style={m.img ? { padding: 0, overflow: 'hidden' } : {}}>{m.img ? <img src={m.img} alt={m.name} style={{ width: '100%', height: '100%', objectFit: 'cover' }} /> : m.i}</div>
              <div className="tm-info">
                <div className="tm-name">{m.name}</div>
                <a href={m.li} target="_blank" rel="noopener noreferrer" className="tm-li">LinkedIn {'\u2192'}</a>
                <p className="tm-bio">{m.bio}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
      <CTABand label="Work with us" title="GET IN<br><em>Touch</em>" btnText="Contact Us →" btnHref="/contact" />
    </>
  )
}